# Generated by Django 6.0.4 on 2026-04-21 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('separador_millares', models.CharField(choices=[(',', 'Coma ,'), ('.', 'Punto .'), (' ', 'Espacio'), ('', 'Vacío')], default=',', max_length=2)),
                ('separador_decimal', models.CharField(choices=[('.', 'Punto .'), (',', 'Coma ,'), (' ', 'Espacio')], default='.', max_length=2)),
                ('decimales', models.IntegerField(default=2)),
                ('formato', models.CharField(choices=[('0 S', '0 S'), ('0S', '0S'), ('S 0', 'S 0'), ('S0', 'S0')], default='0 S', max_length=5)),
                ('tasa_cambio', models.FloatField(default=1.0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('balance', models.FloatField(default=0.0)),
                ('incluir_en_totales', models.BooleanField(default=True)),
                ('mostrar_en_seleccion', models.BooleanField(default=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gasto', 'Gasto'), ('ingreso', 'Ingreso'), ('transferencia', 'Transferencia')], max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('monto', models.FloatField()),
                ('tasa_cambio', models.FloatField(blank=True, null=True)),
                ('monto_destino', models.FloatField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('confirmada', models.BooleanField(default=True)),
                ('incluir_en_informes', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.categoria')),
                ('cuenta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_destino', to='finanzas.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_origen', to='finanzas.cuenta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
