# Generated by Django 6.0.4 on 2026-04-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_alter_moneda_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='finanzas.categoria'),
        ),
    ]
